### ISSUE TITLE
Integration Testing a Consumer

### ISSUE THREAD

**Issue by MissingHandle** [zendesk/racecar#128]
We are starting on integrating Kafka and `racecar` into an app.  Looking at the documentation and the code, it's not clear to me how we can integration test a producer-consumer pair from within our test suite.

that is, while in production the produced events will be coming from an external service, in our test suite we would like to run a consumer, produce what should be an event that matches what will be produced in production, and assert against the expected results of the consumption.

anything that exists for this that y'all can point me to, or a discussion of the challenges of doing so?

both for the gem and the reply, many thanks!

**Comment by breunigs** [comment]
Assuming you're on 2.0 alpha:

1) If you just want to test your behaviour of your implementation, you can use something like this:
```ruby
msg = instance_double(::Rdkafka::Consumer::Message,
  key:       key.to_s,
  payload:   payload ? payload.to_json : nil,
  topic:     topic,
  partition: 0,
  offset:    offset,
)

YourConsumer.new.process_batch([msg, msg])
```

Obviously that's not too great, because it requires you to have internal knowledge about how racecar works, though you can also just dump an example message on production and use whatever it outputs.

2) If you want to cover more code with your integration test, then it becomes hairy relatively quickly. If you start a `Racecar::Runner` (which receives your `Racecar::Consumer`) in a separate thread and mock on rdkafka-ruby level, you might cover some of Racecar's behaviour. But the runner doesn't have a concept of "exit after receiving message", so you'll have to call `stop` at the right time, `raise` from your consumer under test or other such approaches which don't seem too appealing. Additionally you'll mostly have to mock librdkafka away, which also contains a big chunk of logic with regards to retries, offset handling, etc. Long story short, in the current state this approach seems not worth it. 

3) There's obviously the option to run Kafka and a Racecar consumer in a docker-compose or similar environment, then produce an event to Kafka and observe the result. 

From gut feeling I'd not use 2). We never implemented 3) for this project so I don't have code to share.
We're currently using 1) plus a staging environment with alerting to test our projects on top of racecar and it has been fine so far.

**Comment by MissingHandle** [comment]
Thank you very much for the reply.  We're evaluating our options.  We may end up going with (3).  If so, I will aim to update this issue with our findings.

**Comment by MissingHandle** [comment]
So, 

As we near launching Kafka as part of our infrastructure and App development,  I'll summarize what we've ended up doing for posterity.

As for tests that are part of our build, we have settled on approach (1).   Something like approach (2) was attempted, but proved too difficult and not worth the effort.

There is also a local-development win here for approach 3:  We added kafka and zookeeper images to our docker-compose, and we created a very simple ruby producer for local development.

```
# KafkaProducer
# purpose: to be able to send kafka messages from console in local development.

class KafkaProducer
  BASIC_CONFIG = {
    "bootstrap.servers": "kafka:29092",
  }.freeze

  def self.produce(message = {})
    new(BASIC_CONFIG).produce(message)
  end

  def initialize(configuration)
    @configuration = configuration
  end

  def producer
    @producer ||= Rdkafka::Config.new(@configuration).producer
  end

  def produce(topic:, key:, payload:)
    producer.produce(
      topic: topic,
      key: key,
      payload: payload
    )
  end
end
```

We can then, in different term windows:
1) spin up a racecar consumer locally
2) open up a rails console to produce messages using the above producer, taking a sample message from the actual producer. 

This helped us debug our consumer.

also, if anyone is using docker, and is having trouble getting the rdkafka gem to build properly, we needed to compile it from source in our Dockerfile:

```
ENV LIBRDKAFKA_SOURCE https://github.com/edenhill/librdkafka/archive/v1.2.0.zip

RUN curl -L $LIBRDKAFKA_SOURCE -o librdkafka-1.2.0.zip && \
    unzip librdkafka-1.2.0.zip && \
    cd librdkafka-1.2.0 && \
    ./configure --install-deps --source-deps-only && \
    make && \
    make install && \
    ln -s /usr/local/lib/librdkafka* /usr/lib/ && \
    cd .. && \
    rm -rf librdkafka-1.2.0 librdkafka-1.2.0.zip
```

sincerely, 
denverCoder10

**Comment by MissingHandle** [comment]
oh and also, thanks again for the guidance @breunigs !
