### ISSUE TITLE
Datadog instrumentation: Errors in threads do not bubble up to top level traces

### ISSUE THREAD

**Issue by ronan-mch** [zendesk/racecar#172]
I have some traces which contain errors, but the trace itself is marked as ok in Datadog even though these errors are not being rescued. This means that we can't monitor error rates using APM.

**Comment by dasch** [comment]
Can you pinpoint where this happens? Processing errors are always rescued by Racecar, but errors in the fetcher thread should be dealt with intelligently, or the process be killed.

**Comment by ronan-mch** [comment]
Sorry, this is happening in the `process_batch` method.

**Comment by dasch** [comment]
Hmm, here's the culprit:

https://github.com/zendesk/racecar/blob/163497d3e7ac3f71a0af7372501db9cd9c6f3568/lib/racecar/runner.rb#L196-L206

I _remember_ the blocks being shuffled around for some other reason. Can you check out the history? The problem is that `instrument` happens outside of the `with_pause` block. I _think_ we should be able to swap those, but there might be a reason for why it's like it is right now. Intuitively, we would want to treat each attempt as a span methinks.
