### ISSUE TITLE
Starting multiple instances of consumer, but still only one in consumer group

### ISSUE THREAD

**Issue by davich** [zendesk/racecar#203]
So i've been following the readme instructions and trying to get multiple instances running within a consumer group but it's not working.

I run `bundle exec racecar CommentsConsumer` on several terminal windows. But all messages only go to one of them. When I kill the one that it goes to, it goes to another one. I'm publishing messages with a random partition_key (through delivery_boy gem).

I've run `kafka-consumer-groups` to see what's in the group and this is my output
```
$ kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --describe --all-groups

GROUP             TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                     HOST            CLIENT-ID
comments-consumer comments        0          45              45              0               machname-893a4d36-e01c-402d-b3a8-d31d9dbe9d11 /192.168.1.136  machname
```

My consumer class is this
```
class CommentsConsumer < Racecar::Consumer
  subscribes_to "comments"

  def process(message)
    puts "Received message: #{message.value}"
    sleep 1
    puts "Processed message: #{message.value}"
  end
end
```

Any ideas? Thanks

**Comment by Alexander-Blair** [comment]
@davich how did you create the Kafka topic? From the output it suggests there's only one partition, which would explain why messages go to only one consumer at a time

**Comment by davich** [comment]
Thanks for your reply. 

I'm using DeliveryBoy gem to produce messages, and I think that creates the topic automatically.
This is what I'm running:
```
DeliveryBoy.deliver({comment: "my comment #{Time.now}"}.to_json, topic: "comments", partition_key: SecureRandom.uuid)
```

**Comment by Alexander-Blair** [comment]
Ah, OK, Kafka will be auto creating the topics for you. Assuming you're running it in a fairly standard way in development, you can recreate the topic manually with more partitions so that multiple consumers can consume from it:

**Delete topic:**
`kafka-topics --bootstrap-server localhost:9092 --delete --topic comments`
**Ensure the topic is actually deleted:** (if this doesn't work you'll need to ensure that the `delete.topic.enable` in your Kafka configuration)
`kafka-topics --bootstrap-server localhost:9092 --list`
**Recreate the topic with 3 (or however many you want) partitions:**
`kafka-topics --bootstrap-server localhost:9092 --create --topic comments --partitions 3`

And just to expand on the above - you can only have one consumer, per group, per topic partition. Kafka will try to balance the partitions equally between the active consumers, so in the case of a single partition topic, it'll only ever assign that partition to a single consumer. This relates to the fact that the order of messages is only guaranteed to be correct per topic partition, so to ensure messages are consumed in the correct order, only a single consumer can be assigned to a partition.

**Comment by davich** [comment]
Thank you so much @Alexander-Blair ❤️ 

That was the missing piece of the puzzle. It's all working as expected now!
